### ISSUE TITLE
Request failed: unacceptable content-type: text/html

### ISSUE THREAD

**Issue by Nikolxm** [yuantiku/YTKNetwork#288] opened 2016-11-28 08:45 UTC
Error Domain=com.alamofire.error.serialization.response Code=-1016 
"Request failed: unacceptable content-type: text/html"
status code: 200

//original
-  (AFJSONResponseSerializer *)jsonResponseSerializer {
    if (!_jsonResponseSerializer) {
        _jsonResponseSerializer = [AFJSONResponseSerializer serializer];
        _jsonResponseSerializer.acceptableStatusCodes = _allStatusCodes;
    }
    return _jsonResponseSerializer;
}

//set acceptableContentTypes
-  (AFJSONResponseSerializer *)jsonResponseSerializer {
    if (!_jsonResponseSerializer) {
        _jsonResponseSerializer = [AFJSONResponseSerializer serializer];
        _jsonResponseSerializer.acceptableStatusCodes = _allStatusCodes;
        _jsonResponseSerializer.acceptableContentTypes = [NSSet setWithObjects:@"text/html",@"application/json", @"text/json" ,@"text/javascript", nil];

    }
    return _jsonResponseSerializer;
}

**Comment by skyline75489** [comment] 2016-11-30 15:18
Duplicate of #216, #233, #250.

**Closed by skyline75489** 2016-11-30 15:18 UTC
